### PR TITLE
Add test and gene region in the ASEperRegion and add to the Wiki

### PR DESCRIPTION
**Pull request by adriaan-vd-graaf**
This pull request is an improvement to the previous cell type specific expression framework.
Documentation has been enhanced in the wiki, the ASEperRegion is now considered correct based on internal simulations and has added a testing and gene region

### CODE REVIEW

**Comment by PatrickDeelen** [comment]
@adriaan-vd-graaf can you please first fix the merge conflict so that I can do the merge.

**Comment by adriaan-vd-graaf** [comment]
Fixed and merged. Next time I'll make sure the branch can be merged.

**Comment by adriaan-vd-graaf** [comment]
Or should I, next time, not merge  my own stuff?

**Comment by PatrickDeelen** [comment]
No you should never do this!

**Pull request merged**
